apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: engram

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml
  - netpol.yaml
  - servicemonitor.yaml
  - neo4j.yaml
  - redis.yaml
  - cronjob-decay.yaml

commonLabels:
  app.kubernetes.io/part-of: engram
  app.kubernetes.io/managed-by: kustomize
