"""PostgreSQL schema for canonical memory state.

The existing :mod:`engram.storage.postgres` schema is intentionally limited to
the event/control plane.  This module owns the first canonical-memory schema
slice so it can be migrated independently without making the control-plane
store a filesystem-shaped repository.

All canonical rows carry ``tenant_id``.  Canonical UUIDs are generated by the
repository rather than by a PostgreSQL extension; that keeps migrations
portable across managed PostgreSQL 16 installations while still providing
stable, database-enforced UUID identities.
"""

from __future__ import annotations

# Keep this SQL idempotent: tests and local bootstrap code may run it more than
# once.  The Alembic revision executes the same statements after revision
# 0001, where the ``events`` table is already present.
CANONICAL_SCHEMA_SQL = """
CREATE UNIQUE INDEX IF NOT EXISTS idx_events_tenant_event
    ON events(tenant_id, event_id);

CREATE TABLE IF NOT EXISTS canonical_mutations (
    id UUID PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    source_event_id TEXT NOT NULL CHECK (length(btrim(source_event_id)) > 0),
    mutation_type TEXT NOT NULL CHECK (length(btrim(mutation_type)) > 0),
    status TEXT NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'APPLIED', 'FAILED')),
    revision BIGINT NOT NULL CHECK (revision > 0),
    result_memory_id UUID,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    result JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    applied_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, source_event_id, mutation_type)
);
CREATE INDEX IF NOT EXISTS idx_canonical_mutations_tenant_status
    ON canonical_mutations(tenant_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_canonical_mutations_tenant_event
    ON canonical_mutations(tenant_id, source_event_id, mutation_type);

CREATE TABLE IF NOT EXISTS memory_nodes (
    id UUID PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    memory_type TEXT NOT NULL
        CHECK (memory_type IN (
            'ENTITY', 'EPISODE', 'SESSION_SUMMARY', 'COLLECTION', 'PROJECT',
            'FILE', 'CLASS', 'FUNCTION', 'METHOD', 'EXTERNAL_MODULE',
            'EVENT', 'FACT', 'DOCUMENT', 'DIRECTORY', 'PROFILE', 'PREFERENCE'
        )),
    canonical_name TEXT,
    canonical_uri TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN (
            'ACTIVE', 'HISTORICAL', 'RETIRED', 'MERGED', 'LOW_CONFIDENCE',
            'CONFLICTING', 'DELETED'
        )),
    current_version_id UUID,
    revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
    origin_event_id TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, canonical_uri),
    FOREIGN KEY (tenant_id, origin_event_id)
        REFERENCES events(tenant_id, event_id)
        ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_memory_nodes_tenant_status
    ON memory_nodes(tenant_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_nodes_tenant_type
    ON memory_nodes(tenant_id, memory_type, canonical_name);
CREATE INDEX IF NOT EXISTS idx_memory_nodes_tenant_uri
    ON memory_nodes(tenant_id, canonical_uri);
CREATE INDEX IF NOT EXISTS idx_memory_nodes_tenant_origin_event
    ON memory_nodes(tenant_id, origin_event_id)
    WHERE origin_event_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS memory_versions (
    id UUID PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    memory_id UUID NOT NULL,
    version_number INTEGER NOT NULL CHECK (version_number > 0),
    body TEXT NOT NULL,
    abstract TEXT,
    asserted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_from TIMESTAMPTZ,
    valid_until TIMESTAMPTZ,
    source_event_id TEXT,
    provenance JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, memory_id, version_number),
    FOREIGN KEY (tenant_id, memory_id)
        REFERENCES memory_nodes(tenant_id, id)
        ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, source_event_id)
        REFERENCES events(tenant_id, event_id)
        ON DELETE RESTRICT,
    CHECK (valid_until IS NULL OR valid_from IS NULL OR valid_until > valid_from)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_memory_versions_tenant_source_event
    ON memory_versions(tenant_id, memory_id, source_event_id)
    WHERE source_event_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_memory_versions_memory_version_desc
    ON memory_versions(tenant_id, memory_id, version_number DESC);
CREATE INDEX IF NOT EXISTS idx_memory_versions_tenant_asserted
    ON memory_versions(tenant_id, asserted_at DESC);

CREATE TABLE IF NOT EXISTS memory_claims (
    id UUID PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    subject_id UUID NOT NULL,
    predicate TEXT NOT NULL CHECK (length(btrim(predicate)) > 0),
    object_entity_id UUID,
    object_value JSONB,
    object_type TEXT NOT NULL
        CHECK (object_type IN (
            'ENTITY', 'STRING', 'TEXT', 'ROLE', 'NUMBER', 'INTEGER', 'FLOAT',
            'BOOLEAN', 'DATE', 'DATETIME', 'JSON', 'LIST'
        )),
    status TEXT NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN (
            'ACTIVE', 'HISTORICAL', 'SUPERSEDED', 'LOW_CONFIDENCE',
            'CONFLICTING', 'RETRACTED'
        )),
    confidence NUMERIC(6, 5)
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    valid_from TIMESTAMPTZ,
    valid_until TIMESTAMPTZ,
    asserted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_event_id TEXT,
    source_version_id UUID,
    source_triplet_index INTEGER CHECK (source_triplet_index IS NULL OR source_triplet_index >= 0),
    supersedes_claim_id UUID,
    superseded_by_claim_id UUID,
    normalized_object_hash TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, subject_id)
        REFERENCES memory_nodes(tenant_id, id)
        ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, object_entity_id)
        REFERENCES memory_nodes(tenant_id, id)
        ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, source_version_id)
        REFERENCES memory_versions(tenant_id, id)
        ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, supersedes_claim_id)
        REFERENCES memory_claims(tenant_id, id)
        ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, superseded_by_claim_id)
        REFERENCES memory_claims(tenant_id, id)
        ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, source_event_id)
        REFERENCES events(tenant_id, event_id)
        ON DELETE RESTRICT,
    CHECK ((object_entity_id IS NULL) <> (object_value IS NULL)),
    CHECK (valid_until IS NULL OR valid_from IS NULL OR valid_until > valid_from)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_memory_claims_tenant_event_triplet
    ON memory_claims(tenant_id, source_event_id, source_triplet_index)
    WHERE source_event_id IS NOT NULL AND source_triplet_index IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_memory_claims_current_subject_predicate
    ON memory_claims(tenant_id, subject_id, predicate, status, valid_from, valid_until);
CREATE INDEX IF NOT EXISTS idx_memory_claims_object_entity
    ON memory_claims(tenant_id, object_entity_id, status)
    WHERE object_entity_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_memory_claims_source_event
    ON memory_claims(tenant_id, source_event_id)
    WHERE source_event_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_memory_claims_logical_fingerprint
    ON memory_claims(
        tenant_id, subject_id, predicate, normalized_object_hash,
        COALESCE(valid_from, '-infinity'::timestamptz),
        COALESCE(valid_until, 'infinity'::timestamptz)
    );

CREATE TABLE IF NOT EXISTS memory_evidence (
    id UUID PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    memory_id UUID NOT NULL,
    claim_id UUID,
    source_event_id TEXT,
    source_session_id TEXT,
    extractor TEXT,
    extractor_version TEXT,
    confidence NUMERIC(6, 5)
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    source_span JSONB,
    source_text_hash TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    idempotency_key TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, id),
    FOREIGN KEY (tenant_id, memory_id)
        REFERENCES memory_nodes(tenant_id, id)
        ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, claim_id)
        REFERENCES memory_claims(tenant_id, id)
        ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, source_event_id)
        REFERENCES events(tenant_id, event_id)
        ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_memory_evidence_tenant_idempotency
    ON memory_evidence(tenant_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_memory_evidence_tenant_claim
    ON memory_evidence(tenant_id, claim_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_evidence_tenant_event
    ON memory_evidence(tenant_id, source_event_id)
    WHERE source_event_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS entity_aliases (
    id UUID PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    entity_id UUID NOT NULL,
    alias TEXT NOT NULL CHECK (length(btrim(alias)) > 0),
    normalized_alias TEXT NOT NULL CHECK (length(btrim(normalized_alias)) > 0),
    confidence NUMERIC(6, 5)
        CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    source_event_id TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, entity_id, normalized_alias),
    FOREIGN KEY (tenant_id, entity_id)
        REFERENCES memory_nodes(tenant_id, id)
        ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, source_event_id)
        REFERENCES events(tenant_id, event_id)
        ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_entity_aliases_tenant_normalized
    ON entity_aliases(tenant_id, normalized_alias, confidence DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_entity_aliases_tenant_entity
    ON entity_aliases(tenant_id, entity_id);

CREATE TABLE IF NOT EXISTS memory_hierarchy (
    id UUID PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    parent_id UUID NOT NULL,
    child_id UUID NOT NULL,
    position INTEGER,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, parent_id, child_id),
    FOREIGN KEY (tenant_id, parent_id)
        REFERENCES memory_nodes(tenant_id, id)
        ON DELETE CASCADE,
    FOREIGN KEY (tenant_id, child_id)
        REFERENCES memory_nodes(tenant_id, id)
        ON DELETE CASCADE,
    CHECK (parent_id <> child_id)
);
CREATE INDEX IF NOT EXISTS idx_memory_hierarchy_tenant_parent
    ON memory_hierarchy(tenant_id, parent_id, position, child_id);
CREATE INDEX IF NOT EXISTS idx_memory_hierarchy_tenant_child
    ON memory_hierarchy(tenant_id, child_id, parent_id);

CREATE TABLE IF NOT EXISTS memory_overviews (
    id UUID PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    scope_id UUID NOT NULL,
    content TEXT NOT NULL,
    input_revision BIGINT NOT NULL CHECK (input_revision > 0),
    model_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, scope_id, input_revision),
    FOREIGN KEY (tenant_id, scope_id)
        REFERENCES memory_nodes(tenant_id, id)
        ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_memory_overviews_tenant_scope_revision
    ON memory_overviews(tenant_id, scope_id, input_revision DESC);

CREATE TABLE IF NOT EXISTS memory_uri_aliases (
    id UUID PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    memory_id UUID NOT NULL,
    uri TEXT NOT NULL CHECK (length(btrim(uri)) > 0),
    alias_type TEXT NOT NULL
        CHECK (alias_type IN ('LEGACY_FILE', 'CANONICAL', 'EXTERNAL', 'REDIRECT', 'OTHER')),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, uri),
    FOREIGN KEY (tenant_id, memory_id)
        REFERENCES memory_nodes(tenant_id, id)
        ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_memory_uri_aliases_tenant_memory
    ON memory_uri_aliases(tenant_id, memory_id, alias_type);

CREATE TABLE IF NOT EXISTS ingest_artifacts (
    id UUID PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    event_id TEXT NOT NULL,
    artifact_type TEXT NOT NULL
        CHECK (artifact_type IN (
            'UPLOAD_ZIP', 'ZIP', 'RAW_EVENT', 'SOURCE_TEXT', 'EXTRACTION',
            'TYPED_CLAIMS', 'NORMALIZED_CLAIMS', 'OTHER'
        )),
    artifact_key TEXT NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    content BYTEA NOT NULL,
    content_hash TEXT NOT NULL CHECK (length(btrim(content_hash)) > 0),
    media_type TEXT NOT NULL DEFAULT 'application/zip'
        CHECK (length(btrim(media_type)) > 0),
    expires_at TIMESTAMPTZ,
    extractor TEXT,
    extractor_version TEXT,
    source_span JSONB,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, event_id, artifact_type, artifact_key),
    FOREIGN KEY (tenant_id, event_id)
        REFERENCES events(tenant_id, event_id)
        ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_ingest_artifacts_tenant_event
    ON ingest_artifacts(tenant_id, event_id, created_at);
CREATE INDEX IF NOT EXISTS idx_ingest_artifacts_tenant_hash
    ON ingest_artifacts(tenant_id, content_hash)
    WHERE content_hash IS NOT NULL;
"""


def schema_statements() -> list[str]:
    """Return executable statements for ``PostgresStore``/Alembic.

    The schema deliberately contains no procedural functions, so splitting on
    semicolons is safe and remains compatible with the repository's existing
    migration bootstrap.
    """

    return [statement.strip() for statement in CANONICAL_SCHEMA_SQL.split(";") if statement.strip()]


__all__ = ["CANONICAL_SCHEMA_SQL", "schema_statements"]
